baseURL = 'https://ntucpc.pages.dev/'
languageCode = 'en-us'
title = '程式解題社'
theme = 'ananke'

Paginate = 3
disableFastRender = true

[[menu.main]]
name = "Interviews"
url = "/interviews/"

[environments]
  [environments.production]
    baseURL = "https://ntucpc.pages.dev/"
  [environments.development]
    baseURL = "http://localhost:1313/"

[params]
  custom_css = ["css/style.css", "css/toc.css"]

[markup.tableOfContents]
  endLevel = 6
  startLevel = 1